    
    link: "Link(" NUMBER ")" | "Link(" NUMBER link_rest ")" | "Link(" link ")"
    
    ?link_first: "null" 
    
    ?link_rest: ", " link
    
    %ignore /\s+/
    %import common.NUMBER


    
    tree_node: "Tree(" label ")" | "Tree(" label ", [" branches "])"

    ?label: NUMBER

    branches: ", " tree_node | tree_node | tree_node ", " tree_node

    %ignore /\s+/
    %import common.NUMBER

